// Project icons. All from Lucide (ISC License, see NOTICE).

import {
  Search,
  Send,
  Paperclip,
  Moon,
  Sun,
  Bell,
  BellOff,
  Pencil,
  Trash2,
  Copy,
  Reply,
  Check,
  CheckCheck,
  SmilePlus,
  Menu,
  ArrowLeft,
  ArrowDown,
  RotateCcw,
  Info,
  X,
  ChevronRight,
  Link,
  Plus,
  AlertCircle,
  Monitor,
  Smartphone,
  Tablet,
  Mic,
  Video,
  Play,
  Pause,
  Phone,
} from 'lucide-react';

// Re-export Lucide icons directly.
export {
  Search as IconSearch,
  Send as IconSend,
  Paperclip as IconAttach,
  Moon as IconMoon,
  Sun as IconSun,
  Bell as IconBell,
  BellOff as IconBellOff,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  Copy as IconCopy,
  Reply as IconReply,
  Check as IconCheck,
  CheckCheck as IconChecks,
  SmilePlus as IconSmilePlus,
  Menu as IconMenu,
  ArrowLeft as IconArrowLeft,
  ArrowDown as IconArrowDown,
  RotateCcw as IconRotateCcw,
  Info as IconInfo,
  X as IconX,
  ChevronRight as IconChevronRight,
  Link as IconLink,
  Plus as IconPlus,
  AlertCircle as IconAlertCircle,
  Monitor as IconMonitor,
  Smartphone as IconSmartphone,
  Tablet as IconTablet,
  Mic as IconMic,
  Video as IconCamera,
  Play as IconPlay,
  Pause as IconPause,
  Phone as IconPhone,
  Video as IconVideoCam,
};
